# TCL File Generated by Component Editor 13.0sp1
# Tue Aug 04 22:28:16 BST 2026
# DO NOT MODIFY


# 
# count_leading_ones "count_leading_ones" v1.0
#  2026.08.04.22:28:16
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module count_leading_ones
# 
set_module_property DESCRIPTION ""
set_module_property NAME count_leading_ones
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME count_leading_ones
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL count_leading_ones
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file CountLeadingOnes.v VERILOG PATH CountLeadingOnes.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave_0
# 
add_interface nios_custom_instruction_slave_0 nios_custom_instruction end
set_interface_property nios_custom_instruction_slave_0 clockCycle 0
set_interface_property nios_custom_instruction_slave_0 operands 2
set_interface_property nios_custom_instruction_slave_0 ENABLED true
set_interface_property nios_custom_instruction_slave_0 EXPORT_OF ""
set_interface_property nios_custom_instruction_slave_0 PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave_0 ncs_clk clk Input 1
add_interface_port nios_custom_instruction_slave_0 ncs_clk_en clk_en Input 1
add_interface_port nios_custom_instruction_slave_0 ncs_reset reset Input 1
add_interface_port nios_custom_instruction_slave_0 ncs_dataa dataa Input 32
add_interface_port nios_custom_instruction_slave_0 ncs_result result Output 32

