# TCL File Generated by Component Editor 13.0sp1
# Wed Aug 05 01:50:57 BST 2026
# DO NOT MODIFY


# 
# nci_pwm_controller "nci_pwm_controller" v1.0
#  2026.08.05.01:50:57
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module nci_pwm_controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME nci_pwm_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME nci_pwm_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ci_pwm_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file ci_pwm_controller.v VERILOG PATH ci_pwm_controller.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter PWM_BASE_ADDR STD_LOGIC_VECTOR 557056
set_parameter_property PWM_BASE_ADDR DEFAULT_VALUE 557056
set_parameter_property PWM_BASE_ADDR DISPLAY_NAME PWM_BASE_ADDR
set_parameter_property PWM_BASE_ADDR TYPE STD_LOGIC_VECTOR
set_parameter_property PWM_BASE_ADDR UNITS None
set_parameter_property PWM_BASE_ADDR ALLOWED_RANGES 0:17179869183
set_parameter_property PWM_BASE_ADDR HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point nios_custom_instruction_slave_0
# 
add_interface nios_custom_instruction_slave_0 nios_custom_instruction end
set_interface_property nios_custom_instruction_slave_0 clockCycle 0
set_interface_property nios_custom_instruction_slave_0 operands 2
set_interface_property nios_custom_instruction_slave_0 ENABLED true
set_interface_property nios_custom_instruction_slave_0 EXPORT_OF ""
set_interface_property nios_custom_instruction_slave_0 PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave_0 ncs_clk clk Input 1
add_interface_port nios_custom_instruction_slave_0 ncs_clk_en clk_en Input 1
add_interface_port nios_custom_instruction_slave_0 ncs_reset reset Input 1
add_interface_port nios_custom_instruction_slave_0 ncs_start start Input 1
add_interface_port nios_custom_instruction_slave_0 ncs_dataa dataa Input 32
add_interface_port nios_custom_instruction_slave_0 ncs_result result Output 32
add_interface_port nios_custom_instruction_slave_0 ncs_done done Output 1


# 
# connection point avalon_master_0
# 
add_interface avalon_master_0 avalon start
set_interface_property avalon_master_0 addressUnits SYMBOLS
set_interface_property avalon_master_0 associatedClock clock
set_interface_property avalon_master_0 associatedReset reset
set_interface_property avalon_master_0 bitsPerSymbol 8
set_interface_property avalon_master_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_master_0 burstcountUnits WORDS
set_interface_property avalon_master_0 doStreamReads false
set_interface_property avalon_master_0 doStreamWrites false
set_interface_property avalon_master_0 holdTime 0
set_interface_property avalon_master_0 linewrapBursts false
set_interface_property avalon_master_0 maximumPendingReadTransactions 0
set_interface_property avalon_master_0 readLatency 0
set_interface_property avalon_master_0 readWaitTime 1
set_interface_property avalon_master_0 setupTime 0
set_interface_property avalon_master_0 timingUnits Cycles
set_interface_property avalon_master_0 writeWaitTime 0
set_interface_property avalon_master_0 ENABLED true
set_interface_property avalon_master_0 EXPORT_OF ""
set_interface_property avalon_master_0 PORT_NAME_MAP ""
set_interface_property avalon_master_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_master_0 avm_address address Output 32
add_interface_port avalon_master_0 avm_write write Output 1
add_interface_port avalon_master_0 avm_read read Output 1
add_interface_port avalon_master_0 avm_writedata writedata Output 32
add_interface_port avalon_master_0 avm_readdata readdata Input 32
add_interface_port avalon_master_0 avm_waitrequest waitrequest Input 1

